sql-port: 3306
sql-user: user
sql-password: password
sql-database: database
sql-hostname: localhost

# Port to run web charts on. Should be greater than 1000.
chart-port: 2015

# Enable web charts
chart-enabled: true

# Your server hostname
chart-url: mc.example.com

# The total number of orders a player can list
listing-limit: 25

# Message to show players who have reached limit of listings
listing-limit-msg: You've reached the maximum number of %d buy and sell orders.