name: mcex
main: xyz.mcex.plugin.McexPlugin
version: 0.2.0
depend: [Vault]
commands:
    mcex:
        description: Base command for all MCEX-related things. Do /mcex help for more information.
        usage: /mcex [pageNo]
        permission: mcex.cmd
        permission-message: No permission.